version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: xo
    versions:
    - 0.38.1
    - 0.38.2
  - dependency-name: purgecss
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: np
    versions:
    - 7.3.0
    - 7.4.0
