name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    env:
      CI: true

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ./node_modules
        key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('./yarn.lock') }}
    - name: yarn install, lint, and test
      run: yarn
    - name: sanity check
      run: yarn example
    - name: lint
      run: yarn lint
    - name: tests uncached
      run: |
        rm -rf node_modules/.cache
        yarn test
    - name: tests cached
      run: yarn test
