name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
    env:
      CI: true

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache dependencies paths
      uses: actions/cache@v2
      with:
        path: |
          ./node_modules
        key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('./yarn.lock') }}
    - name: Install dependencies
      run: yarn
    - name: Sanity check
      run: yarn example
    - name: Code Quality
      run: yarn lint
    - name: Test (uncached)
      run: |
        rm -rf node_modules/.cache
        yarn test
    - name: Test (cached)
      run: yarn test
